services:
    # PHP
    php:
        build: .docker/php
        ports:
            - 5173:5173
            - 8080:8080
        volumes:
            - .:/var/www:cached

    # Nginx
    nginx:
        image: nginx:alpine
        ports:
            - 81:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    # Mailpit
    mail:
        image: axllent/mailpit:latest
        ports:
            - 1025:1025
            - 8025:8025

    # Redis
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - .docker/redis/data:/data
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    # PostgreSQL
    db:
        image: postgres:17-alpine
        ports:
            - 5432:5432
        volumes:
            - .docker/db/data:/var/lib/postgresql/data
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWORD=laravel
            - POSTGRES_DB=laravel
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "laravel", "-U", "laravel"]
            retries: 3
            timeout: 5s

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        depends_on:
            - db

    # DATABASE (MySQL)
    # db:
    #     image: mysql/mysql-server:8.0
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel
    #         MYSQL_USER: laravel
    #         MYSQL_PASSWORD: laravel
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping", "-proot"]
    #         retries: 3
    #         timeout: 5s

    # phpMyAdmin
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - 8081:80
    #     links:
    #         - db
    #     environment:
    #         PMA_HOST: db
    #         PMA_PORT: 3306
    #         PMA_ARBITRARY: 1
    #     volumes:
    #         - .docker/phpmyadmin/sessions:/sessions

    # Adminer
    # adminer:
    #     image: adminer
    #     ports:
    #         - 9090:8080
    #     depends_on:
    #         - db
